### ISSUE TITLE
Version incompatibilities and identification problem with 3.11 and 3.11.2

### ISSUE THREAD

**Issue by lelegard** [VisionAdvanceTechnologyInc/vatek_sdk_2#9]
Hello,

Initial symptom: Because of the publication of VATek-Linux-x86_64-3.11.2.tgz, the CI jobs for the TSDuck project fail on Linux ([see here](https://github.com/tsduck/tsduck/actions/runs/11176858800/job/31071120087) for instance).

Root cause: The function `vatek_device_list_enum` now needs an additional parameter and compilation fails.

Introducing additional parameters can be required. However, the way it has been done breaks many things and highlights various version management issues. 

1. Keeping upward compatibility is important. With C, where we don't have default values for parameters (unlike C++), adding a new parameter breaks all existing code. The usual practice is to define a new version of the function, such as `vatek_device_list_enum_2` or something similar. The code is moved to the new function. The old function is kept and calls the new function with a decent default value for the new parameter.
2. Versions shall be clearly identified so that the applications can use `#if` directives to call the right function (or provide the right number of parameters), based on the version. Here, the symbol `VATEK_VERSION` has version 31000 (3.10) instead of 31102. The version of the API shall be carefully increased at each version, without exception. Here, we cannot differentiate versions 3.10, 3.11 and 3.11.2. Since versions 3.11 and 3.11.2 have incompatible API's, applications are broken.
3. Using GitHub releases, each release shall be clearly identified. Here, there is no release 3.11.2. The version 3.11 was _renamed_ 3.11.2 and the file `VATek-Linux-x86_64-3.11.2.tgz` replaced its 3.11 counterpart. However, the Windows setup and the source archive remained at version 3.11.

As a consequence, building an application such as TSDuck using the latest online version of libvatek results in the following situation:

- On Windows, the 3.11 setup installed (despite the version name 3.11.2 on Github) and the build works.
- On Linux x86_64, the binary archive `VATek-Linux-x86_64-3.11.2.tgz` is downloaded and the build fails.
- On Linux arm64 (and all non-Intel platforms), the source archive `v3.11.zip` is downloaded and the build works.
- On macOS, the situation is unclear. In Homebrew, `libvatek` is in the "autobump" list. This means that a new version is automatically created when the periodic autobump job in Homebrew detects a new release on Github. Here, there is no new release, just an existing one with different name but same tag as previously. We will see the impact in a few hours, after the autobump job completes. Hopefully, nothing will happen...

Fixing these issues is important and urgent since the CI of TSDuck is currently broken.

My recommendation:

1. Restore `VATek-Linux-x86_64-3.11.tgz` in the Github release and rename the release back to 3.11. This will fix the broken applications.
2. Update `VATEK_VERSION` to 31102 (or higher) and establish a step in the release process to enforce a correct value in all future releases.
3. If possible, move the code of `vatek_device_list_enum` into some new `vatek_device_list_enum_???` function with a new parameter. Keep the old `vatek_device_list_enum` with the same number of parameters and only call the new function from the old one. Also please document the new parameter.
4. Create a distinct release 3.11.2 (or higher) on Github with updated archives for Linux and Windows.

Thank you

**Comment by lelegard** [comment]
Thank you for reverting the "latest version" label to 3.10. The CI jobs pass now.

**Comment by a83912a** [comment]
@lelegard 
Hello, I apologize for the trouble I caused yesterday. Due to my oversight, an unfinished version was uploaded as the latest. I currently have an issue. Due to technical problems, the multi-device functionality for WinUSB on the Windows system has not been completed yet, but the multi-device functionality for VATek devices using LibUSB on Linux has been finished. I would like Linux users to start using and testing it first, and I wanted to ask for your opinion.

If I release the latest version 3.11.2, with the Linux binary as 3.11.2 and also update the Windows binary to 3.11.2, since the vatek_device_list_enum_??? function with new parameters will be added based on your suggestion, but only Linux systems can properly handle multi-device setups, I will note that this feature is only available on Linux systems. Would this be acceptable to you? 

Thank you.

**Comment by lelegard** [comment]
Hello Richie,

No problem. "Shit happens" is a basic rule of computing. The most important point is not the problem but the speed of reaction and mitigation. You reverted quite rapidly to a stable version and that's great.

My recommendations would be twofold. First, the universal principles:

- A release is final. It shall not be modified, renamed or have an asset replaced. Last minute problems happen. In that case, a new release with a minor increment shall be created. You may update the description of the previous release with something like "this release X.Y is buggy, use X.Y.1".
- A release shall be clearly identified, especially with a C/C++ macro value in the case of a library.
- A release shall be homogeneous across systems. An installer or source code shall be available for all OS. The same level of API should be provided. If distinct OS cannot provide the same level of functionality, just document it.

Second, application to the current situation:

- Create a new distinct release, 3.11.2 or whatever. Make sure that the tag is properly created in the repo and binaries are provided for Windows and Linux (x86).
- Make sure that `VATEK_VERSION` is properly updated.
- Create a new `vatek_device_list_enum_something` function with the new parameter. Make it available to all OS, including Windows. If the new parameter is currently useless on Windows, no problem, just document it for now. At some point, you will find a solution for WinUSB and you will implement it in a new release.

If possible, submit a pull request for the `vatek` code in TSDuck to use the new function based on some `#if VATEK_VERSION >= 311xx`.

A few questions:

- What is the purpose of the new parameter in `vatek_device_list_enum_something`?
- In order to document the limitation on Windows, what is it exactly? Simultaneous usage of two VATek devices? Does it work if several devices are plugged in but you use only one at a time, using its device index?
- Do you see any relation with issue https://github.com/tsduck/tsduck/issues/1508 where VATek and Dektec USB devices had a conflict?

**Comment by lelegard** [comment]
@a83912a, I know have problems with the recent release 3.12. The CI now breaks on Windows. See log here: https://github.com/tsduck/tsduck/actions/runs/11289392540/job/31399157494

The errors are all linker errors with "unresolved external symbol libusb_XXX". It seems that the compilation of an application on Windows is now trying to use libusb instead of WinUSB. Since libusb is not present, not referenced in the link, it fails.

The release which is marked as "latest" is still 3.10 and it is installed on Linux systems. So, CI jobs pass on Linux.

On Windows, however, the script `install-prerequisites.ps1` which is run at the beginning of a CI job installs the release of libvatek which was published the most recently. In that case, this is version 3.12. And it fails.

Arguably, `install-prerequisites.ps1` should install the release of libvatek with the "latest" label. I just updated the script and pushed the commit on Github. The CI job is currently running but the initialization log shows that it correctly installed libvatek 3.10 (the one marked as "latest").

So, TSDuck is now safe as long as the release of libvatek which is marked as "latest" remains 3.10.

Please check the problem in version 3.12 and release an update with which an application compiles on Windows.

**Comment by lelegard** [comment]
@a83912a 

The version 3.12.0 is broken. It has been grabbed by the Homebrew autobump job and it failed.

See https://github.com/Homebrew/homebrew-core/pull/193741

**Comment by lelegard** [comment]
@a83912a, we have a huge problem with version 3.12.0.

The mess I anticipated has happened. During the period of time version 3.12.0 had "latest" label, the autobump job of Homebrew had run over it and, now, libvatek 3.12.0 is propagated to all macOS systems in the world (including mine).

And this breaks all TSDuck builds.

First, the function `vatek_device_list_enum` still has the additional parameter which breaks the compatibility with the previous version.

Second, and __much worse__, the symbol `VATEK_VERSION` is still 31000 (3.10.0) in `vatek_base.h`. I already mentioned that about version version 3.11. It is not acceptable to still have it in 3.12.

You cannot break the compatibility in existing applications and not even give the opportunity to these applications to adapt their code based on your version, because this version is incorrectly identified.

Unfortunately, this situation leaves me no other choice that disabling VATek support in TSDuck until a proper version of libvatek is provided. The first and initial condition is that a version shall ALWAYS be properly identified in a symbol such as `VATEK_VERSION`.

You must realise that, even if you fix the situation in a future version, there will always be a risk that a user tries to compile TSDuck with a version of libvatek 3.10, 3.11, 3.12 and all these versions are indistinguishable (same `VATEK_VERSION`) but are incompatible. This is the kind of mess that potentially lasts forever.

After publishing a clean new release, please provide a pull request to TSDuck to adapt to the new version. Make sure that the code is backward compatible, meaning that you properly test `VATEK_VERSION` to call the old or new function. The new TSDuck code shall compile correctly whichever is the version of libvatek (except 3.12 which will remain a pain forever).

In this PR, also remove the definition which disables VATek support in `src/libtsduck/base/cpp/tsPreConfiguration.h`.

**Comment by a83912a** [comment]
@lelegard ,Sorry, I just recently got a Mac device, but I encountered a problem. I want to upload Homebrew, but it doesn't allow me to manually upload libvatek 3.12, as this project is currently set to upload automatically. Even after I re-release VATek 3.12, it won't upload automatically every three hours. Is there a way for me to manually upload it? Can you guide me on how to do this? Thank you.
<img width="642" alt="image" src="https://github.com/user-attachments/assets/6c398dc6-bbf4-4bfd-8459-9c34f9253e17">

**Comment by lelegard** [comment]
Please read what I wrote in a previous post: A release is FINAL, it cannot be modified or re-released.

This is not only a matter of Homebrew, this is the same for winget or any Linux distro. This is a universal principle. Once a binary+source is named X.Y, this X.Y remains that binary+source forever.

In the case of HomeBrew, there is a current version, say 3.11. When the autobump job detects a release with another version, say 3.12, it grabs the corresponding git tag v3.12 in the repository and the source code with that tag becomes libvatek 3.12 FOREVER.

Again, I wrote that in a previous post, there is no such thing as "re-release". If you want to release a modification, this _must be a new release_, even a minor one.

This is also why I strongly recommended to thoroughly test a set of code on all targets before creating a release. Once it's out, it's out forever. If you modify a release afterwards, you create a mess because, in the field, there will be two deliveries, with distinct behaviours and same identification. Please, NEVER do that.

Also note what I wrote in a previous post: take advantage of GitHub Continuous Integration environment (GitHub Actions workflows). They offer access for free to Linux, macOS and Windows CI runners. You push a commit, candidate for a release, the CI runs on all platforms, all tests are done everywhere. If you are satisfied with the result, and only if you are satisfied, then you can publish a release.

Again, version 3.12 is dead, forever, forget about it. Create a version 3.12.1 or 3.13 with all the fixes (and after tests).

**Comment by lelegard** [comment]
Thank you @a83912a for the new release (and PR for TSDuck). The build works now.

However, there is still a problem with that release. It is incorrectly identified here:

~~~
#define VATEK_VERSION 31210
~~~

This is the encoding for 3.12.10, not 3.12.1 (which should be 31201). See the result with TSDuck:
~~~
$ tsp --version=vatek
libvatek version 3.12.10
~~~

But _please_ do not change or rename the release. We already saw the inconsistencies it generates.

This is not a big issue for now, so don't change anything. However, this means that if you need to release a new minor version, it must be 3.12.11, __not 3.12.2__, to ensure an increasing set of version numbers.

I close this issue as resolved.
